theme: jekyll-theme-minimal

name: Salem, I'm Hit
description: Amber and Tony have a mic and we're sorry
url: http://salemimhit.com
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

plugins:
  - jekyll-feed
