theme: jekyll-theme-minimal

name: Salem, I'm Hit!
description: Amber and Tony have a mic and we're sorry
url: http://salemimhit.com


<a href="https://itunes.apple.com/us/podcast/salem-im-hit/id674304763?mt=2&ign-mpt=uo%3D4"/>iTunes</a>
<br><a href="http://www.stitcher.com/podcast/salem-im-hit"/>Stitcher</a><br><hr>
<a href="http://twitter.com/salemimhit" rel="Twitter">Twitter</a>
<hr>
Playing Games:<br>
<a href="http://www.twitch.tv/salemimhit" rel="Live on Twitch">Twitch</a>
<br>
<a href="https://www.youtube.com/user/salemimhit" rel="Later on Youtube">YouTube</a>
<br>
