theme: jekyll-theme-minimal

name: Salem, I'm Hit!
description: Salem, I'm Hit Podcast

Amber and Tony Have mics and we are sorry

[iTunes](https://itunes.apple.com/us/podcast/salem-im-hit/id674304763?mt=2&amp;ign-mpt=uo%3D4)  
[Stitcher](http://www.stitcher.com/podcast/salem-im-hit)  
[Twitter](http://twitter.com/salemimhit)  

### Playing Games:
[Twitch](http://www.twitch.tv/salemimhit)  
[YouTube](https://www.youtube.com/user/salemimhit)  
-------------------------------------------------------
url: http://salemimhit.com


