theme: jekyll-theme-minimal

name: Salem, I'm Hit!
description: > # this means to ignore newlines until "baseurl:"
  Amber and Tony Have mics and we are sorry <a target="_blank" href="http://www.makersacademy.com">
  Makers Academy</a>
# baseurl: "" # the subpath of your site, e.g. /blog
url: http://salemimhit.com
twitter_username: salemimhit




