theme: jekyll-theme-minimal

name: Salem, I'm Hit!
brand : Salem, I'm Hit!

description: > # this means to ignore newlines until "baseurl:"
  Amber and Tony Have mics and we are sorry 
  <a target="_blank" https://itunes.apple.com/us/podcast/salem-im-hit/id674304763?mt=2&amp;ign-mpt=uo%3D4">
  iTunes</a>
   <a target="_blank" http://www.stitcher.com/podcast/salem-im-hit">
  Stitcher</a>
   
# baseurl: "" # the subpath of your site, e.g. /blog
url: http://salemimhit.com
twitter_username: salemimhit

author : Amber Spence
paginate : 10

favicon :
  enabled : true
  local :
    enabled : true
    partial_url : false
    type : false
  remote :
    enabled : false
    full_url : https://res.cloudinary.com/dxqlm0d3h/image/upload/v1547325655/favicon.ico
    type : ico

sections:
  brief_bio :
    enabled : true
    image :
      enabled : false
      url : false
    content :
      enabled : true
    social_links :
      enabled : true
    github_projects :
      enabled : false
  social_links :
    enabled : false
  github_projects :
    enabled : false
  external_links :
    enabled : true
  archive :
    enabled : false
  categories :
    enabled : false
  tags :
    enabled : false


social_links :
  follow_name : Me
  links :
    - link :
      enabled : false
      name : Facebook
      font_awesome_icon : icon-facebook
      url : https://www.facebook.com/
    - link :
      enabled : false
      name : GitHub
      font_awesome_icon : icon-github-alt
      url : https://github.com/
    - link :
      enabled : false
      name: Google+
      font_awesome_icon : icon-google-plus
      url : https://plus.google.com/
    - link :
      enabled : false
      name : Linkedin
      font_awesome_icon : icon-linkedin
      url : http://www.linkedin.com/
    - link :
      enabled : false
      font_awesome_icon : icon-pinterest
      name : Pinterest
      url : http://www.pinterest.com
    - link :
      enabled : true
      name : Twitter
      font_awesome_icon : icon-twitter
      url : https://www.twitter.com/salemimhit
      
      
  font_awesome :
  enabled : true
  css : font-awesome.min.css


rss :
  enabled : true
  managing_editor :
    enabled : false
    managing_editor : false
  webmaster :
    enabled : false
    webmaster : false
  ttl :
    enabled : true
    ttl : 300
  image :
    enabled : false
    image : false
    
    
analytics :
  enabled : false
  google_analytics :
    enabled : false
    tracking_id : UA-132397321-1   

